import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Routes, Route, Navigate } from 'react-router-dom';
import AdminLayout from '@/layouts/AdminLayout';
import AuthLayout from '@/layouts/AuthLayout';
import PublicLayout from '@/layouts/PublicLayout';
import Dashboard from '@/admin/Dashboard';
import CommunityPrograms from '@/admin/community/CommunityPrograms';
import Outreach from '@/admin/community/Outreach';
import Volunteers from '@/admin/community/Volunteers';
import CommunityCalendar from '@/admin/community/Calendar';
import ServiceRequests from '@/admin/public-service/ServiceRequests';
import Appointments from '@/admin/public-service/Appointments';
import SeminarRegistrations from '@/admin/public-service/SeminarRegistrations';
import HazardReports from '@/admin/public-service/HazardReports';
import Login from '@/auth/Login';
import Register from '@/auth/Register';
import ForgotPassword from '@/auth/ForgotPassword';
import PublicHome from '@/public/pages/Home';
import PublicServices from '@/public/pages/Services';
import PublicSeminars from '@/public/pages/Seminars';
import PublicHazards from '@/public/pages/Hazards';
import PublicAppointments from '@/public/pages/Appointments';
import PublicInfo from '@/public/pages/Info';
import IncidentList from '@/admin/incidents/IncidentList';
import IncidentRecord from '@/admin/incidents/IncidentRecord';
import IncidentDetail from '@/admin/incidents/IncidentDetail';
import IncidentAnalytics from '@/admin/incidents/IncidentAnalytics';
import PersonnelList from '@/admin/personnel/PersonnelList';
import DutyRoster from '@/admin/personnel/DutyRoster';
import Attendance from '@/admin/personnel/Attendance';
import LeaveManagement from '@/admin/personnel/LeaveManagement';
import TrainingRecords from '@/admin/personnel/TrainingRecords';
import EquipmentList from '@/admin/equipment/EquipmentList';
import VehicleList from '@/admin/equipment/VehicleList';
import Maintenance from '@/admin/equipment/Maintenance';
import FuelMonitoring from '@/admin/equipment/FuelMonitoring';
import Establishments from '@/admin/inspections/Establishments';
import InspectionSchedule from '@/admin/inspections/InspectionSchedule';
import Certificates from '@/admin/inspections/Certificates';
import InspectionReports from '@/admin/inspections/InspectionReports';
import Compliance from '@/admin/compliance/Compliance';
import HydrantRegistry from '@/admin/hydrants/HydrantRegistry';
import GISMap from '@/admin/hydrants/GISMap';
import HydrantInspections from '@/admin/hydrants/HydrantInspections';
import Memoranda from '@/admin/documents/Memoranda';
import DocumentRepository from '@/admin/documents/DocumentRepository';
import IncomingDocuments from '@/admin/documents/IncomingDocuments';
import OutgoingDocuments from '@/admin/documents/OutgoingDocuments';
import ReportsDashboard from '@/admin/reports/ReportsDashboard';
import IncidentReports from '@/admin/reports/IncidentReports';
import ReportsInspectionReports from '@/admin/reports/InspectionReports';
import PersonnelReports from '@/admin/reports/PersonnelReports';
import Settings from '@/admin/Settings';
import UserManagement from '@/admin/UserManagement';
import AuditTrail from '@/admin/AuditTrail';
export default function App() {
    return (_jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(Navigate, { to: "/public", replace: true }) }), _jsxs(Route, { path: "/public", element: _jsx(PublicLayout, {}), children: [_jsx(Route, { index: true, element: _jsx(PublicHome, {}) }), _jsx(Route, { path: "services", element: _jsx(PublicServices, {}) }), _jsx(Route, { path: "appointments", element: _jsx(PublicAppointments, {}) }), _jsx(Route, { path: "seminars", element: _jsx(PublicSeminars, {}) }), _jsx(Route, { path: "hazards", element: _jsx(PublicHazards, {}) }), _jsx(Route, { path: "info", element: _jsx(PublicInfo, {}) })] }), _jsxs(Route, { path: "/auth", element: _jsx(AuthLayout, {}), children: [_jsx(Route, { index: true, element: _jsx(Navigate, { to: "login", replace: true }) }), _jsx(Route, { path: "login", element: _jsx(Login, {}) }), _jsx(Route, { path: "register", element: _jsx(Register, {}) }), _jsx(Route, { path: "forgot", element: _jsx(ForgotPassword, {}) })] }), _jsxs(Route, { path: "/admin", element: _jsx(AdminLayout, {}), children: [_jsx(Route, { index: true, element: _jsx(Navigate, { to: "incidents", replace: true }) }), _jsx(Route, { path: "dashboard", element: _jsx(Dashboard, {}) }), _jsx(Route, { path: "public-service", element: _jsx(ServiceRequests, {}) }), _jsx(Route, { path: "public-service/appointments", element: _jsx(Appointments, {}) }), _jsx(Route, { path: "public-service/seminars", element: _jsx(SeminarRegistrations, {}) }), _jsx(Route, { path: "public-service/hazards", element: _jsx(HazardReports, {}) }), _jsx(Route, { path: "inspections", element: _jsx(Establishments, {}) }), _jsx(Route, { path: "inspections/schedule", element: _jsx(InspectionSchedule, {}) }), _jsx(Route, { path: "inspections/certificates", element: _jsx(Certificates, {}) }), _jsx(Route, { path: "inspections/reports", element: _jsx(InspectionReports, {}) }), _jsx(Route, { path: "incidents", element: _jsx(IncidentList, {}) }), _jsx(Route, { path: "incidents/new", element: _jsx(IncidentRecord, {}) }), _jsx(Route, { path: "incidents/:id", element: _jsx(IncidentDetail, {}) }), _jsx(Route, { path: "incidents/analytics", element: _jsx(IncidentAnalytics, {}) }), _jsx(Route, { path: "compliance", element: _jsx(Compliance, {}) }), _jsx(Route, { path: "personnel", element: _jsx(PersonnelList, {}) }), _jsx(Route, { path: "personnel/roster", element: _jsx(DutyRoster, {}) }), _jsx(Route, { path: "personnel/attendance", element: _jsx(Attendance, {}) }), _jsx(Route, { path: "personnel/leave", element: _jsx(LeaveManagement, {}) }), _jsx(Route, { path: "personnel/training", element: _jsx(TrainingRecords, {}) }), _jsx(Route, { path: "equipment", element: _jsx(EquipmentList, {}) }), _jsx(Route, { path: "vehicles", element: _jsx(VehicleList, {}) }), _jsx(Route, { path: "maintenance", element: _jsx(Maintenance, {}) }), _jsx(Route, { path: "fuel", element: _jsx(FuelMonitoring, {}) }), _jsx(Route, { path: "hydrants", element: _jsx(HydrantRegistry, {}) }), _jsx(Route, { path: "hydrants/map", element: _jsx(GISMap, {}) }), _jsx(Route, { path: "hydrants/inspections", element: _jsx(HydrantInspections, {}) }), _jsx(Route, { path: "community", element: _jsx(CommunityPrograms, {}) }), _jsx(Route, { path: "community/outreach", element: _jsx(Outreach, {}) }), _jsx(Route, { path: "community/volunteers", element: _jsx(Volunteers, {}) }), _jsx(Route, { path: "community/calendar", element: _jsx(CommunityCalendar, {}) }), _jsx(Route, { path: "reports", element: _jsx(ReportsDashboard, {}) }), _jsx(Route, { path: "reports/incidents", element: _jsx(IncidentReports, {}) }), _jsx(Route, { path: "reports/inspections", element: _jsx(ReportsInspectionReports, {}) }), _jsx(Route, { path: "reports/personnel", element: _jsx(PersonnelReports, {}) }), _jsx(Route, { path: "documents", element: _jsx(DocumentRepository, {}) }), _jsx(Route, { path: "documents/incoming", element: _jsx(IncomingDocuments, {}) }), _jsx(Route, { path: "documents/outgoing", element: _jsx(OutgoingDocuments, {}) }), _jsx(Route, { path: "documents/memoranda", element: _jsx(Memoranda, {}) }), _jsx(Route, { path: "users", element: _jsx(UserManagement, {}) }), _jsx(Route, { path: "audit", element: _jsx(AuditTrail, {}) }), _jsx(Route, { path: "settings", element: _jsx(Settings, {}) })] })] }));
}
