import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { useState } from 'react';
import { ArrowLeft, Mail } from 'lucide-react';
export default function ForgotPassword() {
    const [sent, setSent] = useState(false);
    const [email, setEmail] = useState('');
    function handleSubmit(e) {
        e.preventDefault();
        setSent(true);
    }
    return (_jsxs("div", { className: "bg-white border border-gray-200 rounded-xl shadow-sm", children: [_jsxs("div", { className: "px-6 py-5 border-b border-gray-100 text-center", children: [_jsx("h1", { className: "text-lg font-bold text-gray-900", children: "Reset Password" }), _jsx("p", { className: "text-sm text-gray-500 mt-0.5", children: sent ? 'Reset link sent' : 'Enter your registered email address' })] }), !sent ? (_jsxs("form", { onSubmit: handleSubmit, className: "p-6 space-y-4", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-1", children: "Email Address" }), _jsx("input", { type: "email", value: email, onChange: (e) => setEmail(e.target.value), className: "w-full px-3 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-red-500 focus:border-red-500", placeholder: "you@example.com", required: true }), _jsx("p", { className: "text-xs text-gray-400 mt-1", children: "We'll send a password reset link to your email. The link expires in 24 hours." })] }), _jsx("button", { type: "submit", className: "w-full py-2.5 bg-red-700 text-white text-sm font-medium rounded-lg hover:bg-red-800 transition-colors", children: "Send Reset Link" })] })) : (_jsxs("div", { className: "p-6 text-center", children: [_jsx("div", { className: "w-14 h-14 rounded-full bg-green-100 text-green-600 flex items-center justify-center mx-auto mb-4", children: _jsx(Mail, { size: 24 }) }), _jsx("h2", { className: "text-base font-semibold text-gray-900 mb-1", children: "Check your email" }), _jsxs("p", { className: "text-sm text-gray-500 mb-2", children: ["We've sent a password reset link to ", _jsx("strong", { className: "text-gray-900", children: email }), "."] }), _jsxs("p", { className: "text-xs text-gray-400 mb-5", children: ["Didn't receive the email? Check your spam folder or", ' ', _jsx("button", { onClick: () => setSent(false), className: "text-red-700 hover:text-red-800 font-medium", children: "try again" }), "."] }), _jsx("button", { onClick: () => setSent(false), className: "w-full py-2.5 bg-gray-100 text-gray-700 text-sm font-medium rounded-lg hover:bg-gray-200 transition-colors", children: "Send to a different email" })] })), _jsx("div", { className: "px-6 pb-5 text-center", children: _jsxs(Link, { to: "/auth/login", className: "text-sm text-red-700 hover:text-red-800 font-medium inline-flex items-center gap-1", children: [_jsx(ArrowLeft, { size: 14 }), " Back to sign in"] }) })] }));
}
